# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guid', models.TextField()),
                ('current_path', models.TextField()),
                ('target_path', models.TextField()),
                ('start_time', models.IntegerField()),
                ('received_bytes', models.IntegerField()),
                ('total_bytes', models.IntegerField()),
                ('state', models.IntegerField()),
                ('danger_type', models.IntegerField()),
                ('interrupt_reason', models.IntegerField()),
                ('hash', models.BinaryField()),
                ('end_time', models.IntegerField()),
                ('opened', models.IntegerField()),
                ('referrer', models.TextField()),
                ('site_url', models.TextField()),
                ('tab_url', models.TextField()),
                ('tab_referrer_url', models.TextField()),
                ('http_method', models.TextField()),
                ('by_ext_id', models.TextField()),
                ('by_ext_name', models.TextField()),
                ('etag', models.TextField()),
                ('last_modified', models.TextField()),
                ('mime_type', models.CharField(max_length=255)),
                ('original_mime_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'downloads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadsSlices',
            fields=[
                ('download_id', models.IntegerField(primary_key=True, serialize=False)),
                ('offset', models.IntegerField(primary_key=True)),
                ('received_bytes', models.IntegerField()),
            ],
            options={
                'db_table': 'downloads_slices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadsUrlChains',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chain_index', models.IntegerField(primary_key=True)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'downloads_url_chains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordSearchTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.IntegerField()),
                ('url_id', models.IntegerField()),
                ('lower_term', models.TextField()),
                ('term', models.TextField()),
            ],
            options={
                'db_table': 'keyword_search_terms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'segments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentUsage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_slot', models.IntegerField()),
                ('visit_count', models.IntegerField()),
            ],
            options={
                'db_table': 'segment_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('visit_count', models.IntegerField()),
                ('typed_count', models.IntegerField()),
                ('last_visit_time', models.IntegerField()),
                ('hidden', models.IntegerField()),
                ('favicon_id', models.IntegerField()),
            ],
            options={
                'db_table': 'urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_time', models.IntegerField()),
                ('from_visit', models.IntegerField(blank=True, null=True)),
                ('transition', models.IntegerField()),
                ('visit_duration', models.IntegerField()),
            ],
            options={
                'db_table': 'visits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitSource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.IntegerField()),
            ],
            options={
                'db_table': 'visit_source',
                'managed': False,
            },
        ),
    ]
